### ISSUE TITLE
linkerd2-proxy drop the connection to RPC endpoint outside of cluster

### ISSUE THREAD

**Issue by Bedotech** [linkerd/linkerd2#1778]
### What is the issue?

When my pod try to make an RPC connection the connection fail, the request transposed as curl command in another pod, or in the linkerd proxy works.

The same container if running from my PC can correctly call the url and working nicely

If i remove the sidecar container with: `linkerd.io/auto-inject: disabled` everything works well.
### Logs, error output, etc
```
ERR! proxy={server=out listen=127.0.0.1:4140 remote=172.20.135.33:41216} linkerd2_proxy::proxy::http::router service error: an error occurred trying to connect: Connection refused (os error 111)
INFO admin={bg=tls-config} linkerd2_proxy::transport::tls::config loaded TLS configuration.
INFO admin={bg=tls-config} linkerd2_proxy::transport::tls::config loaded TLS configuration.
INFO admin={bg=resolver} linkerd2_proxy::transport::connect DNS resolved DnsName(DnsName(DNSName("proxy-api.linkerd.svc.cluster.local"))) to 172.16.178.59
```
If i tap on the deployment i see:
```text
req id=0:0 proxy=out src=172.20.135.33:59424 dst=**********:80 tls=no_identity :method=POST :authority=example.replaced.com:path=/
end id=0:0 proxy=out src=172.20.135.33:59424 dst=**********:80 tls=no_identity reset-error=2 duration=0µs response-length=0B
```

#### `linkerd check` output

```text
kubernetes-api: can initialize the client..................................[ok]
kubernetes-api: can query the Kubernetes API...............................[ok]
kubernetes-api: is running the minimum Kubernetes API version..............[ok]
linkerd-api: control plane namespace exists................................[ok]
linkerd-api: control plane pods are ready..................................[ok]
linkerd-api: can initialize the client.....................................[ok]
linkerd-api: can query the control plane API...............................[ok]
linkerd-api[kubernetes]: control plane can talk to Kubernetes..............[ok]
linkerd-api[prometheus]: control plane can talk to Prometheus..............[ok]
linkerd-version: can determine the latest version..........................[ok]
linkerd-version: cli is up-to-date.........................................[ok]
linkerd-version: control plane is up-to-date...............................[ok]

Status check results are [ok]

```

### Environment

- Kubernetes Version: 1.10
- Cluster Environment: Minikube
- Linkerd version: edge-18.10.3

### Additional context

I using auto injection feature.

**Comment by klingerf** [comment]
Thanks for reporting this, @Bedotech!

In your environment, can you try manually injecting your deployment to see if it encounters the same issue? Something like: `linkerd inject deploy.yaml | kubectl apply -f -`. It's no problem to manually inject in an auto inject environment: the proxy injector will skip pods that are already injected.

If the pod is able to route requests correctly using `linkerd inject`, but not with auto injection, that will indicate that this is a problem with auto inject. If neither approach works, then something else is misconfigured.

**Comment by Bedotech** [comment]
No the problem isn't about auto inject, still the same error

**Comment by klingerf** [comment]
@Bedotech Are you still seeing this issue with the latest [Linkerd 2.1 release](https://github.com/linkerd/linkerd2/releases/tag/stable-2.1.0)? There have been a lot of stability fixes in the latest release.

**Comment by Bedotech** [comment]
Hi @klingerf i will test this the next week, but i have a question:

I have to use always DNS resolution over environments variable for discovery my services? 
because the RPC endpoint have ip that is hardcoded in the config and i notice other service with DNS resolution still working.

**Comment by klingerf** [comment]
I chatted with @Bedotech a bit more in slack to get more information about his setup. He's using linkerd with auto-inject and TLS enabled, and is seeing issues when trying to connect to MySQL. I'm pretty sure he's running into a proxy issue that's being fixed in linkerd/linkerd2-proxy#158.

**Comment by Bedotech** [comment]
i report here some update i've posted on slack: the linkerd/linkerd2-proxy#158 fix multiple issue i have.

I have specific use case, i use helm for deploy so the auto inject feature is a must have, i can use the edge version but some problem still, for example i have a micro service that have connection to RabbitMQ and is accessible via HTTP, i notice the AMPQ protocol can't connect to the rabbit broker, with your fix the problem is solved, but is really hard to me set `--skip-outbound-ports` and `--linkerd-version`  on automatic injected deployment i have to do this manually.

So test is really complicated and now i haven't the time to build a test case, i will use linkerd in production when all pending feature is released, is some months i follow the product and is really awesome!

**Comment by klingerf** [comment]
Hey @Bedotech, great, thanks for the update! I really appreciate you trying out the fix from linkerd/linkerd2-proxy#158, and I'm glad it fixed the MySQL issue you were seeing. We're planning on shipping that as part of an edge release later today, which should hopefully help with additional testing in your setup.

I'm not sure what the issue with AMQP is, but if setting `--skip-outbound-ports` fixes the issue, I just wanted to mention that you can configure the proxy-injector to skip that port automatically on all configs, by installing linkerd with `linkerd install --tls optional --proxy-auto-inject --skip-outbound-ports xxxx`.

**Comment by hawkw** [comment]
As far as I know, AMQP _should_ work fine with Linkerd's proxy without skipping protocol detection, as it's a client-speaks-first protocol. The proxy will simply treat it as an unrecognized protocol, and proxy the raw TCP connection.

However, if the proxy is causing problems with AMQP traffic, that's probably a bug. If this is the case, we should consider opening a new ticket to track that specifically.

**Comment by klingerf** [comment]
@Bedotech I'm going to close this, since it sounds like the MySQL issue is fixed. Would you mind opening a separate issue if you're still seeing dropped connections for other services?
