### ISSUE TITLE
Multicluster installed on Azure Kubernetes does not appear to see its Targets

### ISSUE THREAD

**Issue by allensiho** [linkerd/linkerd2#4730]
### What is the issue?
Multicluster installed on Azure Kubernetes does not appear to see its Targets

### How can it be reproduced?
We have AKS clusters on the same VNET in different subnets..
No network policies or security groups are assigned

I created the certificates using step
* step certificate create identity.{our-linkerd-ns}.cluster.local root.crt root.key --profile root-ca --no-password --insecure
* step certificate create identity.{our-linkerd-ns}.cluster.local issuer.crt issuer.key --profile intermediate-ca --not-after 8760h --no-password --insecure --ca root.crt --ca-key root.key

Installing linkerd on both clusters
* linkerd install -L {our-linkerd-ns} --registry {OuReg} --disable-heartbeat | kubectl apply -f -

Installing multicluster and confirming gateway and mirror services are rolled out
* linkerd multicluster install -L {our-linkerd-ns} --registry {OuReg}  | kubectl apply -f -

Linking the clusters
* linkerd --context=cluster1 multicluster link --cluster-name cluster1 -L {our-linkerd-ns} |  kubectl --context=cluster2 apply -f -

### Logs, error output, etc
Checking the logs of the service mirror I see 

```
time="2020-07-07T09:37:59Z" level=warning msg="Gateway returned unexpected status 503. Marking as unhealthy" probe-key=linkerd-multicluster-linkerd-gateway-r...
```

Adding more debug logs to the multicluster gateway I see

```
[ 76770.231898129s] DEBUG inbound:accept{peer.addr=10.225.96.132:61260}: linkerd2_app_core::accept_error: Accept failed error=request timed out
[ 76772.136698205s] DEBUG inbound:accept{peer.addr=10.225.96.132:61311}: linkerd2_proxy_transport::tls::accept: attempting TLS handshake
[ 76772.823232557s] DEBUG daemon:admin{listen.addr=0.0.0.0:4191}:accept{peer.addr=10.225.96.163:34322}: linkerd2_proxy_transport::tls::accept: attempting TLS handshake
[ 76773.138022013s] DEBUG inbound:accept{peer.addr=10.225.96.132:61311}: linkerd2_app_core::accept_error: Accept failed error=request timed out
[ 76773.744706372s] DEBUG daemon:admin{listen.addr=0.0.0.0:4191}:accept{peer.addr=10.225.96.163:34370}: linkerd2_proxy_transport::tls::accept: attempting TLS handshake
[ 76774.230509954s] DEBUG inbound:accept{peer.addr=10.225.96.132:61342}: linkerd2_proxy_transport::tls::accept: attempting TLS handshake
[ 76774.314204293s] DEBUG inbound:accept{peer.addr=10.225.96.163:39400}: linkerd2_proxy_transport::tls::accept: attempting TLS handshake
[ 76774.314322392s] DEBUG inbound:accept{peer.addr=10.225.96.163:39400}: linkerd2_app_inbound::require_identity_for_ports: port=8888 peer.id=None(NoPeerName(NotProvidedByRemote)) id_required=false
[ 76774.314442190s] DEBUG inbound:accept{peer.addr=10.225.96.163:39400}:source{target.addr=10.225.96.172:8888}:http1{port=8888 keep_alive=true wants_h1_upgrade=false was_absolute_form=false}: linkerd2_app_inbound::prevent_loop: addr=10.225.96.172:8888 self.port=4143
[ 76774.314534588s] DEBUG inbound: linkerd2_proxy_http::client: method=GET uri=http://10.225.96.172:8888/health-local version=HTTP/1.1 headers={"host": "10.225.96.172:8888", "user-agent": "kube-probe/1.16", "accept-encoding": "gzip"}
[ 76775.231139485s] DEBUG inbound:accept{peer.addr=10.225.96.132:61342}: linkerd2_app_core::accept_error: Accept failed error=request timed out
[ 76777.136633503s] DEBUG inbound:accept{peer.addr=10.225.96.132:61360}: linkerd2_proxy_transport::tls::accept: attempting TLS handshake
[ 76778.138075438s] DEBUG inbound:accept{peer.addr=10.225.96.132:61360}: linkerd2_app_core::accept_error: Accept failed error=request timed out
[ 76778.241636880s] DEBUG inbound:accept{peer.addr=10.225.96.163:39632}: linkerd2_proxy_transport::tls::accept: attempting TLS handshake
[ 76778.241844777s] DEBUG inbound:accept{peer.addr=10.225.96.163:39632}: linkerd2_app_inbound::require_identity_for_ports: port=8888 peer.id=None(NoPeerName(NotProvidedByRemote)) id_required=false
[ 76778.242115573s] DEBUG inbound:accept{peer.addr=10.225.96.163:39632}:source{target.addr=10.225.96.172:8888}:http1{port=8888 keep_alive=true wants_h1_upgrade=false was_absolute_form=false}: linkerd2_app_inbound::prevent_loop: addr=10.225.96.172:8888 self.port=4143
[ 76778.242192972s] DEBUG inbound: linkerd2_cache: services=0 dropped=1
[ 76778.242207572s] DEBUG inbound: linkerd2_cache: Caching new service
[ 76778.242290571s] DEBUG inbound: linkerd2_proxy_http::client: method=GET uri=http://10.225.96.172:8888/heal
th-local version=HTTP/1.1 headers={"host": "10.225.96.172:8888", "user-agent": "kube-probe/1.16", "accept-encoding": "gzip"}
```

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-addons
--------------
√ 'linkerd-config-addons' config map exists

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

linkerd-multicluster-source
---------------------------
√ service mirror controller is running
√ service mirror controller ClusterRoles exist
√ service mirror controller ClusterRoleBindings exist
√ service mirror controller Roles exist
√ service mirror controller RoleBindings exist
√ service mirror controller ServiceAccounts exist
√ service mirror controller has required permissions
√ service mirror controller can access target clusters
× all target cluster gateways are alive
    Some gateways are not alive:
    * cluster: [cluster1], gateway: [linkerd-multicluster/linkerd-gateway]
    see https://linkerd.io/checks/#l5d-multicluster-target-gateways-alive for hints
√ clusters share trust anchors
√ multicluster daisy chaining is avoided
√ all mirror services have endpoints
√ all gateway mirrors have endpoints
√ remote: all referenced gateways are valid

linkerd-multicluster-target
---------------------------
√ all cluster gateways are valid
```

### Environment

- Kubernetes Version:
- Cluster Environment: (GKE, AKS, kops, ...) 
AKS
- Host OS:
Linux
- Linkerd version:
Client version: edge-20.7.1
Server version: unavailable

**Comment by cpretzer** [comment]
@allensiho Thanks for filing this.

During our slack conversation you mentioned that there were some `BadCertificate` errors in the proxy logs. Can you add those here as well?

**Comment by zaharidichev** [comment]
@allensiho  I just tried that on Azure with a custom linkerd namespace, etc and it all worked for me: 

```
CLUSTER           NAMESPACE             NAME             ALIVE    NUM_SVC  LATENCY_P50  LATENCY_P95  LATENCY_P99
cluster-1-zahari  linkerd-multicluster  linkerd-gateway  True           0          4ms          9ms         10ms
```

Can you give us a bit more logs from the proxy. Namely if you can give us more logs from the proxy of the service mirror controller on your source cluster. In Slack you mentioned that you had some trouble with certs that was fixed after you resterted pods. Did you restart the service mirror controller pod as well?

**Comment by cpretzer** [comment]
@allensiho thanks for the chat today, I hope it was helpful.

I'm putting notes here to keep track of the steps we took:
- Got the public IPs of the `linkerd-gateway` LoadBalancer in the east:
```bash
kubectl get svc -n linkerd-multicluster linkerd-gateway --context=east
```

- Next we used that IP in a curl container from from the cluster in the west
```bash
curl https://<public-ip-address>:4143
curl https://<public-ip-address>:4181
```

Both requests returned a 503 error

- We tried the same requests using the node IP address and also got a 503 error:
```bash
curl https://<node-ip-address>:4143
curl https://<node-ip-address>:4181
```

- We turned up the proxy log-level for the linkerd-gateway in the east to debug and ran the curl commands which showed that the proxy was receiving requests from XXX.XXX.XXX.132 and XXX.XXX.XXX.163. Both of those IP addresses belong to pods created by the `azure-cni` daemonset

- Ran curl against the node IP address and got a 470 HTTP status which is unassigned according to the RFC

The next steps are to:
- Talk with the team who set up the clusters to find out how the networking is configured
- Run the `pod-info` [services](https://linkerd.io/2/tasks/multicluster/index.html#installing-the-test-services) on the clusters to make sure that we can get responses from the services that are deployed outside the context of the `linkerd-gateway` and `linkerd-service-mirror`

Thanks again for helping to debug this, it will help people who have environments similar to yours.

**Comment by cpretzer** [comment]
@allensiho from our slack conversation and debug session, it sounds like this is a connectivity issue between the clusters that is unrelated to Linkerd, so I'm going to close this ticket.

If you and your IT team are able to establish an SSH tunnel or other mechanism for allowing access between the clusters on the public IP of the load balancer and this issue persists, please add your notes to this ticket and we'll pick up where we left off
